#ifndef INC_MYDEFINE_H_
#define INC_MYDEFINE_H_

#include "myHeader.h"
#include "cmsis_gcc.h"

#define	_USER_DEFINE_TIM_UVCAPSS htim6
#define _USER_DEFINE_I2C_INA219	hi2c2
#define _USER_DEFINE_I2C_LCD	hi2c2
//*================================================  DEFINE OUTPUT ====================================================-*/
//for Debug
#define TX_V_WritePin(logic)	__NOP()//HAL_GPIO_WritePin(TX_V_GPIO_Port, TX_V_Pin, logic)

#define FAN_ON 			HAL_GPIO_WritePin(FAN_GPIO_Port, FAN_Pin, 1)
#define FAN_OFF 		HAL_GPIO_WritePin(FAN_GPIO_Port, FAN_Pin, 0)

#define MOTOR_IN1_ON 		HAL_GPIO_WritePin(MOTOR_IN1_GPIO_Port, MOTOR_IN1_Pin, 1)
#define MOTOR_IN1_OFF 		HAL_GPIO_WritePin(MOTOR_IN1_GPIO_Port, MOTOR_IN1_Pin, 0)
#define MOTOR_IN1_TOG 		HAL_GPIO_TogglePin(MOTOR_IN1_GPIO_Port, MOTOR_IN1_Pin)
#define MOTOR_IN1_STT 		HAL_GPIO_ReadPin(MOTOR_IN1_GPIO_Port, MOTOR_IN1_Pin)

#define MOTOR_IN2_ON 		HAL_GPIO_WritePin(MOTOR_IN2_GPIO_Port, MOTOR_IN2_Pin, 1)
#define MOTOR_IN2_OFF 		HAL_GPIO_WritePin(MOTOR_IN2_GPIO_Port, MOTOR_IN2_Pin, 0)
#define MOTOR_IN2_TOG 		HAL_GPIO_TogglePin(MOTOR_IN2_GPIO_Port, MOTOR_IN2_Pin)
#define MOTOR_IN2_STT 		HAL_GPIO_ReadPin(MOTOR_IN2_GPIO_Port, MOTOR_IN2_Pin)

//RELAY
#define RL_COM_ON 		HAL_GPIO_WritePin(RL_COM_GPIO_Port, RL_COM_Pin, 1)
#define RL_COM_OFF 		HAL_GPIO_WritePin(RL_COM_GPIO_Port, RL_COM_Pin, 0)
#define RL_COM_TOG 		HAL_GPIO_TogglePin(RL_COM_GPIO_Port, RL_COM_Pin)
#define RL_COM_STT 		HAL_GPIO_ReadPin(RL_COM_GPIO_Port, RL_COM_Pin)

#define RL_SS_STEAM_ON 		HAL_GPIO_WritePin(RL_SS_STEAM_GPIO_Port, RL_SS_STEAM_Pin, 1)
#define RL_SS_STEAM_OFF 	HAL_GPIO_WritePin(RL_SS_STEAM_GPIO_Port, RL_SS_STEAM_Pin, 0)
#define RL_SS_STEAM_TOG 	HAL_GPIO_TogglePin(RL_SS_STEAM_GPIO_Port, RL_SS_STEAM_Pin)
#define RL_SS_STEAM_STT 	HAL_GPIO_ReadPin(RL_SS_STEAM_GPIO_Port, RL_SS_STEAM_Pin)

#define RL_DRAIN_On 		HAL_GPIO_WritePin(RL_DRAIN_GPIO_Port, RL_DRAIN_Pin, 1)
#define RL_DRAIN_Off 		HAL_GPIO_WritePin(RL_DRAIN_GPIO_Port, RL_DRAIN_Pin, 0)
#define RL_DRAIN_TOG 		HAL_GPIO_TogglePin(RL_DRAIN_GPIO_Port, RL_DRAIN_Pin)
#define RL_DRAIN_STT 		HAL_GPIO_ReadPin(RL_DRAIN_GPIO_Port, RL_DRAIN_Pin)

#define RL_WHIRL_On 		HAL_GPIO_WritePin(RL_WHIRL_GPIO_Port, RL_WHIRL_Pin, 1)
#define RL_WHIRL_Off 		HAL_GPIO_WritePin(RL_WHIRL_GPIO_Port, RL_WHIRL_Pin, 0)
#define RL_WHIRL_TOG 		HAL_GPIO_TogglePin(RL_WHIRL_GPIO_Port, RL_WHIRL_Pin)
#define RL_WHIRL_STT 		HAL_GPIO_ReadPin(RL_WHIRL_GPIO_Port, RL_WHIRL_Pin)

#define RL_AIR_ON 		HAL_GPIO_WritePin(RL_AIR_GPIO_Port, RL_AIR_Pin, 1)
#define RL_AIR_OFF 		HAL_GPIO_WritePin(RL_AIR_GPIO_Port, RL_AIR_Pin, 0)
#define RL_AIR_TOG 		HAL_GPIO_TogglePin(RL_AIR_GPIO_Port, RL_AIR_Pin)
#define RL_AIR_STT		HAL_GPIO_ReadPin(RL_AIR_GPIO_Port, RL_AIR_Pin)

#define RL_STEAM100_ON 		HAL_GPIO_WritePin(RL_STEAM100_GPIO_Port, RL_STEAM100_Pin, 1)
#define RL_STEAM100_OFF 	HAL_GPIO_WritePin(RL_STEAM100_GPIO_Port, RL_STEAM100_Pin, 0)
#define RL_STEAM100_TOG 	HAL_GPIO_TogglePin(RL_STEAM100_GPIO_Port, RL_STEAM100_Pin)
#define RL_STEAM100_STT 	HAL_GPIO_ReadPin(RL_STEAM100_GPIO_Port, RL_STEAM100_Pin)

#define RL_STEAM50_ON 		HAL_GPIO_WritePin(RL_STEAM50_GPIO_Port, RL_STEAM50_Pin, 1)
#define RL_STEAM50_OFF 		HAL_GPIO_WritePin(RL_STEAM50_GPIO_Port, RL_STEAM50_Pin, 0)
#define RL_STEAM50_TOG 		HAL_GPIO_TogglePin(RL_STEAM50_GPIO_Port, RL_STEAM50_Pin)
#define RL_STEAM50_STT 		HAL_GPIO_ReadPin(RL_STEAM50_GPIO_Port, RL_STEAM50_Pin)

#define RL_SOL_COM_ON 		HAL_GPIO_WritePin(RL_SOL_COM_GPIO_Port, RL_SOL_COM_Pin, 1)
#define RL_SOL_COM_OFF 		HAL_GPIO_WritePin(RL_SOL_COM_GPIO_Port, RL_SOL_COM_Pin, 0)
#define RL_SOL_COM_TOG 		HAL_GPIO_TogglePin(RL_SOL_COM_GPIO_Port, RL_SOL_COM_Pin)
#define RL_SOL_COM_STT 		HAL_GPIO_ReadPin(RL_SOL_COM_GPIO_Port, RL_SOL_COM_Pin)

//OUTPUT FET
#define FET_DOME_LIGHT_ON 	HAL_GPIO_WritePin(FET_DOME_LIGHT_GPIO_Port, FET_DOME_LIGHT_Pin, 0)
#define FET_DOME_LIGHT_OFF 	HAL_GPIO_WritePin(FET_DOME_LIGHT_GPIO_Port, FET_DOME_LIGHT_Pin, 1)
#define FET_DOME_LIGHT_TOG 	HAL_GPIO_TogglePin(FET_DOME_LIGHT_GPIO_Port, FET_DOME_LIGHT_Pin)
#define FET_DOME_LIGHT_STT 	!HAL_GPIO_ReadPin(FET_DOME_LIGHT_GPIO_Port, FET_DOME_LIGHT_Pin)

#define FET_SOL_AF_ON 		HAL_GPIO_WritePin(FET_SOL_AF_GPIO_Port, FET_SOL_AF_Pin, 0)
#define FET_SOL_AF_OFF 		HAL_GPIO_WritePin(FET_SOL_AF_GPIO_Port, FET_SOL_AF_Pin, 1)
#define FET_SOL_AF_TOG 		HAL_GPIO_TogglePin(FET_SOL_AF_GPIO_Port, FET_SOL_AF_Pin)
#define FET_SOL_AF_STT 		!HAL_GPIO_ReadPin(FET_SOL_AF_GPIO_Port, FET_SOL_AF_Pin)

#define FET_SOL_STEAM_ON 	HAL_GPIO_WritePin(FET_SOL_STEAM_GPIO_Port, FET_SOL_STEAM_Pin, 0)
#define FET_SOL_STEAM_OFF 	HAL_GPIO_WritePin(FET_SOL_STEAM_GPIO_Port, FET_SOL_STEAM_Pin, 1)
#define FET_SOL_STEAM_TOG 	HAL_GPIO_TogglePin(FET_SOL_STEAM_GPIO_Port, FET_SOL_STEAM_Pin)
#define FET_SOL_STEAM_STT 	!HAL_GPIO_ReadPin(FET_SOL_STEAM_GPIO_Port, FET_SOL_STEAM_Pin)

//SIGNAL DRAIN SENSOR
#define DRAINSS_SIGNAL_HI 	HAL_GPIO_WritePin(SSDRAIN_SIGNAL_GPIO_Port, SSDRAIN_SIGNAL_Pin, 1)
#define DRAINSS_SIGNAL_LOW 	HAL_GPIO_WritePin(SSDRAIN_SIGNAL_GPIO_Port, SSDRAIN_SIGNAL_Pin, 0)
#define DRAINSS_SIGNAL_TOG 	HAL_GPIO_TogglePin(SSDRAIN_SIGNAL_GPIO_Port, SSDRAIN_SIGNAL_Pin)
#define DRAINSS_SIGNAL_STT 	HAL_GPIO_ReadPin(SSDRAIN_SIGNAL_GPIO_Port, SSDRAIN_SIGNAL_Pin)

//SIGNAL WATER SENSOR
#define WATERSS_SIGNAL_HI 	HAL_GPIO_WritePin(SSWATER_SIGNAL_GPIO_Port, SSWATER_SIGNAL_Pin, 1)
#define WATERSS_SIGNAL_LOW 	HAL_GPIO_WritePin(SSWATER_SIGNAL_GPIO_Port, SSWATER_SIGNAL_Pin, 0)
#define WATERSS_SIGNAL_TOG 	HAL_GPIO_TogglePin(SSWATER_SIGNAL_GPIO_Port, SSWATER_SIGNAL_Pin)
#define WATERSS_SIGNAL_STT 	HAL_GPIO_ReadPin(SSWATER_SIGNAL_GPIO_Port, SSWATER_SIGNAL_Pin)

//OUTPUT IC SWITCH
#define SS_5V_CTRL_ON 		HAL_GPIO_WritePin(SS_5V_CTRL_GPIO_Port, SS_5V_CTRL_Pin, 1)
#define SS_5V_CTRL_OFF 		HAL_GPIO_WritePin(SS_5V_CTRL_GPIO_Port, SS_5V_CTRL_Pin, 0)
#define SS_5V_CTRL_TOG 		HAL_GPIO_TogglePin(SS_5V_CTRL_GPIO_Port, SS_5V_CTRL_Pin)
#define SS_5V_CTIn_STT 		HAL_GPIO_ReadPin(SS_5V_CTRL_GPIO_Port, SS_5V_CTRL_Pin)

//OUTPUT BUZZER
#define BUZ_ON 			HAL_GPIO_WritePin(BUZ_GPIO_Port, BUZ_Pin, 1)
#define BUZ_OFF 		HAL_GPIO_WritePin(BUZ_GPIO_Port, BUZ_Pin, 0)
#define BUZ_TOG 		HAL_GPIO_TogglePin(BUZ_GPIO_Port, BUZ_Pin)
#define BUZ_STT 		HAL_GPIO_ReadPin(BUZ_GPIO_Port, BUZ_Pin)
//OUTPUT LED1
#define LED1_ON		 	HAL_GPIO_WritePin(LED1_YE_GPIO_Port, LED1_YE_Pin, 1)
#define LED1_OFF 		HAL_GPIO_WritePin(LED1_YE_GPIO_Port, LED1_YE_Pin, 0)
#define LED1_TOG 		HAL_GPIO_TogglePin(LED1_YE_GPIO_Port, LED1_YE_Pin)
#define LED1_STT 		HAL_GPIO_ReadPin(LED1_YE_GPIO_Port, LED1_YE_Pin)

//OUTPUT LED1
#define LED2_ON		 	HAL_GPIO_WritePin(LED2_BL_GPIO_Port, LED2_BL_Pin, 1)
#define LED2_OFF 		HAL_GPIO_WritePin(LED2_BL_GPIO_Port, LED2_BL_Pin, 0)
#define LED2_TOG 		HAL_GPIO_TogglePin(LED2_BL_GPIO_Port, LED2_BL_Pin)
#define LED2_STT 		HAL_GPIO_ReadPin(LED2_BL_GPIO_Port, LED2_BL_Pin)

#define LEDG_ON		 	HAL_GPIO_WritePin(LED24V_GREEN_GPIO_Port, LED24V_GREEN_Pin, 0)
#define LEDG_OFF 		HAL_GPIO_WritePin(LED24V_GREEN_GPIO_Port, LED24V_GREEN_Pin, 1)
#define LEDG_TOG 		HAL_GPIO_TogglePin(LED24V_GREEN_GPIO_Port, LED24V_GREEN_Pin)
#define LEDG_STT 		HAL_GPIO_ReadPin(LED24V_GREEN_GPIO_Port, LED24V_GREEN_Pin)

#define LEDB_ON		 	HAL_GPIO_WritePin(LED24V_BLUE_GPIO_Port, LED24V_BLUE_Pin, 0)
#define LEDB_OFF 		HAL_GPIO_WritePin(LED24V_BLUE_GPIO_Port, LED24V_BLUE_Pin, 1)
#define LEDB_TOG 		HAL_GPIO_TogglePin(LED24V_BLUE_GPIO_Port, LED24V_BLUE_Pin)
#define LEDB_STT 		HAL_GPIO_ReadPin(LED24V_BLUE_GPIO_Port, LED24V_BLUE_Pin)

//OUTPUT BLE
#define BLE_EN_ON 		HAL_GPIO_WritePin(BLE_EN_GPIO_Port, BLE_EN_Pin, 1)
#define BLE_EN_OFF 		HAL_GPIO_WritePin(BLE_EN_GPIO_Port, BLE_EN_Pin, 0)
#define BLE_EN_TOG 		HAL_GPIO_TogglePin(BLE_EN_GPIO_Port, BLE_EN_Pin)
#define BLE_EN_STT 		HAL_GPIO_ReadPin(BLE_EN_GPIO_Port, BLE_EN_Pin)

#define BUG_IO_ON 		HAL_GPIO_WritePin(BUG_IO_GPIO_Port, BUG_IO_Pin, 1)
#define BUG_IO_OFF 		HAL_GPIO_WritePin(BUG_IO_GPIO_Port, BUG_IO_Pin, 0)
#define BUG_IO_TOG 		HAL_GPIO_TogglePin(BUG_IO_GPIO_Port, BUG_IO_Pin)
#define BUG_IO_STT 		HAL_GPIO_ReadPin(BUG_IO_GPIO_Port, BUG_IO_Pin)

#define DIMMER_CTRL_ON   	HAL_GPIO_WritePin(DIM_TRIAC_GPIO_Port, DIM_TRIAC_Pin,1)
#define DIMMER_CTRL_OFF  	HAL_GPIO_WritePin(DIM_TRIAC_GPIO_Port, DIM_TRIAC_Pin,0)
#define DIMMER_CTRL_STT  	HAL_GPIO_ReadPin(DIM_TRIAC_GPIO_Port, DIM_TRIAC_Pin)
#define DIMMER_CTRL_TOG		HAL_GPIO_TogglePin(DIM_TRIAC_GPIO_Port, DIM_TRIAC_Pin)

//*============================= DEFINE INPUT =====================================*//
//Trái
#define SWTLEFT_PinStt 		HAL_GPIO_ReadPin(SSDRAIN_SIGNAL_GPIO_Port,SSDRAIN_SIGNAL_Pin)
//Giữa
#define SWTMID_PinStt 		HAL_GPIO_ReadPin(SSDRAIN_LOGIC_GPIO_Port,SSDRAIN_LOGIC_Pin)
//Phải
#define SWTRIGHT_PinStt 	HAL_GPIO_ReadPin(IN_SAFETY_GPIO_Port, IN_SAFETY_Pin)
//IR_trái
#define IRLEFT_PinStt 		HAL_GPIO_ReadPin(IN_JETSW_GPIO_Port, IN_JETSW_Pin)
//IR_Phải
#define IRRIGHT_PinStt 		HAL_GPIO_ReadPin(IN_DRAINSW_GPIO_Port, IN_DRAINSW_Pin)

#define BUTTON_PinStt 		!HAL_GPIO_ReadPin(IN_BUTTON_GPIO_Port, IN_BUTTON_Pin)

#define SSWATER_Logic_PinStt 	HAL_GPIO_ReadPin(SSWATER_LOGIC_GPIO_Port, SSWATER_LOGIC_Pin)

#define INPUT_AC_STT		HAL_GPIO_ReadPin(IN_EL814_GPIO_Port, IN_EL814_Pin)

#endif /* INC_MYDEFINE_H_ */
